[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "QNPI-InRealisticWaveguides"   
version = "0.1.4"                     
description = "Quantum nonlinear parametric interaction in realistic waveguides" 
readme = "README.md"
requires-python = ">=3.9"
license = { text = "MIT" }
authors = [
    { name = "Tim Weiss", email = "timweiss001@gmail.com" }
]

dependencies = [
    "numpy>=1.25.0",
    "scipy>=1.12.1",
    "matplotlib>=3.6.3",
    "tqdm>=4.66.0",
]

[project.urls]
"Homepage" = "https://github.com/TimFWeiss/QNPI-InRealisticWaveguides"
"Bug Tracker" = "https://github.com/TimFWeiss/QNPI-InRealisticWaveguides/issues"

[tool.setuptools.packages.find]
where = ["src"]