[project]
name = "brewinglib-cli"
version = "0.0.1-rc4"
description = "brewinglib's CLI system, a wrapper around Tiangolo's typer."
readme = "README.md"
authors = [
    { name = "Mike Cowie", email = "24739590+mikemcowie@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2.11.7",
    "typer>=0.16.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/brewinglib"]
