[project]
name = "biased"
version = "0.1.1"
description = "Various reusable components, helpers, and utilities which I would like to use in any Python project"
readme = "README.md"
authors = [
    { name = "Dmitry Tatarkin", email = "tatarkin@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
biased = "biased:main"

[build-system]
requires = ["uv_build>=0.8.16,<0.9.0"]
build-backend = "uv_build"
