[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "agent-framework-lab-gaia"
version = "0.0.1a0"
description = "Agent Framework GAIA Benchmark"
authors = [{ name = "Eric Zhu", email = "ekzhu@microsoft.com" }]
readme = "README.md"
license = "MIT"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://pypi.org/project/agent-framework-lab-gaia/"
