[build-system]
requires = [
    "setuptools>=43.0.0",
    "wheel"
]
build-backend = "setuptools.build_meta"


[project]
name = "genocide"
description = "Since 4 march 2019."
version = "206"
authors = [
    {name = "Bart Thate", email = "bthate@dds.nl" },
]
readme = "README.rst"
license = "Unlicense"
classifiers = [ 
    'Development Status :: 3 - Alpha',
    'Operating System :: Unix',
    'Programming Language :: Python',
    'Topic :: Utilities'
]


[project.scripts]
"genocide" = "genocide.__main__:main"


[project.urls]
"home" = "https://pypi.org/project/genocide"
"bugs" = "https://github.com/bthate/genocide/issues"
"source" = "https://github.com/bthate/genocide"


[tool.setuptools]
packages = [
    'genocide',
    'genocide.html',
    'genocide.html.pdf',
    'genocide.html._static',
    'genocide.html._images',
    'genocide.modules'
]
include-package-data = true


[tool.setuptools.package-data]
"genocide.html"         = ["*"]
"genocide.html.pdf"     = ["*"]
"genocide.html._images" = ["*"]
"genocide.html._static" = ["*"]
