[package]
name = "skyblock-repo"
description = "Cargo/Python package to interface with the Skyblock Repo"
keywords = ["skyblock", "hypixel", "hypixel-skyblock"]

version = "1.0.6"
edition = "2024"

license = "MIT"
readme = "README.md"
repository = "https://github.com/SkyblockRepo/RepoRS"
homepage = "https://skyblockrepo.com"
documentation = "https://skyblockrepo.com/docs/integrations"

[lib]
name = "skyblock_repo"
crate-type = ["cdylib", "rlib"]

[features]
default = []

log = ["dep:log"]
python = ["dep:pyo3", "dep:pyo3-async-runtimes"]

[dependencies]
log = { version = "0.4.28", optional = true }
pyo3 = { version = "0.26.0", features = ["extension-module", "experimental-async"], optional = true }
pyo3-async-runtimes = { version = "0.26.0", features = ["tokio-runtime", "attributes"], optional = true }
rustc-hash = "2.1.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
zip = { version = "5.0.0", default-features = false, features = ["deflate"] }
ureq = "3.1.2"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true

[profile.dev]
incremental = true
opt-level = 1
