[tool.poetry]
name = "dtx-models"
version = "0.43.0"
description = "Shared model schemas and YAML-based configurations for the DTX framework."
authors = ["JC <jitendra@detoxio.ai>"]
readme = "README.md"
homepage = "https://docs.detoxio.ai"
packages = [{ include = "dtx_models", from = "src" }]

# Include non-Python files (e.g., YAMLs)
include = [
    "dtx_models/repo/plugins.yml",
    "dtx_models/repo/ai_frameworks.yml",
    "dtx_models/repo/taxonomy.yml",
    "dtx_models/repo/*.yml"
]

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
pydantic = ">=2.11.5,<3.0.0"
pydantic-yaml = ">=1.5.1,<2.0.0"
pyyaml = ">=6.0.2,<7.0.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
