[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "fts-tool"
version = "1.1.0-beta1"
description = "Peer to peer file and directory transfer system"
authors = [
  { name = "Terabase Studios", email = "terabasestudios@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.8"

dependencies = [
    "aiofiles==24.1.0",
    "argcomplete==3.6.2",
    "cryptography==45.0.7",
    "psutil==7.0.0",
    "tqdm==4.67.1",
    "prompt_toolkit==3.0.52",
    "argparse-interface==0.2.0"
]



[project.scripts]
fts = "fts.cli:main"

# add sympy