[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "jntts-cli"  
version = "1.0.2" 
authors = [
  { name="Justin Nguyen ðŸ‡»ðŸ‡³", email="duchuy_1997@hotmail.com" },
]
description = "Má»™t cÃ´ng cá»¥ TTS sá»­ dá»¥ng mÃ´ hÃ¬nh Bark/Suno Ä‘á»ƒ chuyá»ƒn Ä‘á»•i vÄƒn báº£n thÃ nh giá»ng nÃ³i."
readme = "README.md"  
requires-python = ">=3.9"
license = { file = "LICENSE" }
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Topic :: Multimedia :: Sound/Audio :: Speech"
]

# PHáº¦N QUAN TRá»ŒNG NHáº¤T: Dependencies
dependencies = [
    "torch",
    "transformers",
    "sounddevice",
    "numpy",
    "tqdm",
    "pydub",
    "pyfiglet",
    "psutil",
    "pynvml",
    "py-cpuinfo",
    "appdirs"
]

[tool.setuptools.packages.find]
where = ["src"] 
include = ["jntts*"]  

[project.scripts]
jntts-cli = "jntts.main:main"