[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
readme = { file = "README.md", content-type = "text/markdown" }
name = "bgm-toolkit-pro"
version = "0.2.10"
requires-python = ">=3.9"
description = "Bourdieu-inspired gravity model toolkit (Pro core)"
authors = [{name="Arturo Rubalcava"}]
dependencies = [
  "numpy>=1.24",
  "pandas>=2.0",
  "statsmodels>=0.14",
  "openpyxl>=3.1",
  "PyYAML>=6.0",
  "jinja2>=3.1",
]

[project.scripts]
bgm-pro = "bgm_toolkit.cli:main"
bgm-run = "bgm_toolkit.cli:main"


[tool.setuptools.package-dir]
"" = "src"


[tool.setuptools.packages.find]
where = ["src"]
include = ["bgm_toolkit*", "bgm_toolkit_pro*"]

[tool.setuptools]
include-package-data = false
