[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "twilkit"
version = "1.0.1"
description = "Lightweight Python toolkit: validators, colors, decorators, and FlexVar"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "Avi Twil" }
]
keywords = ["validation", "decorators", "colors", "ansi", "toolkit", "utilities"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries",
    "Topic :: Utilities"
]
requires-python = ">=3.10"

[project.urls]
Homepage = "https://github.com/avitwil/twilkit"
Repository = "https://github.com/avitwil/twilkit"
Issues = "https://github.com/avitwil/twilkit/issues"


[project.optional-dependencies]
extra_tools = ["ADVfile-manager>=1.3.1"]
