[project]
name = "ramocate"
version = "1.0.0.1"
description = "Uses C to get memory functions."
authors = [
    { name = "Borne Sanders", email = "b@matrixsystemsgroup.com" }
]
maintainers = [
    { name = "Borne Sanders", email = "b@matrixsystemsgroup.com" }
]
dependencies = []
requires-python = ">=3.11"
readme = "README.md"
license = "MIT"
keywords = ["memory", "hardware", "C", "risky", "fun ngl"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Topic :: System :: Hardware",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Operating System :: OS Independent"
]

[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]
include = ["ramocate*"]

[tool.setuptools.package-data]
"ramocate.compiledlibs" = [
    "ramocatec.c",
    "ramocatedylib.dylib",
    "ramocateso.so",
    "ramocatedll.dll"
]
