[project]
name = "neurobridge"
version = "0.1.9"
description = "Simulador distribuido de redes neuronales spiking en múltiples GPUs"
readme = "README.md"
requires-python = ">=3.8"
license = { text = "MIT" }

authors = [
  { name = "Álvaro González-Redondo", email = "alvarogr@ugr.es" }
]

maintainers = [
  { name = "Álvaro González-Redondo", email = "alvarogr@ugr.es" }
]

keywords = [
  "SNN", "PyTorch", "multi-GPU", "neural simulation", "computational neuroscience"
]

classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Topic :: Scientific/Engineering :: Artificial Intelligence",
  "Intended Audience :: Science/Research"
]

dependencies = [
  "torch>=2.0",
  "numpy",
  "tqdm",
  "matplotlib",
  "scipy",
]

[project.urls]
"Homepage" = "https://github.com/alvaro-gonzalez-redondo/neurobridge"
"Bug Tracker" = "https://github.com/alvaro-gonzalez-redondo/neurobridge/issues"
"Documentation" = "https://github.com/alvaro-gonzalez-redondo/neurobridge/wiki"

