[tool.poetry]
name = "zenius"
version = "0.6.1"
description = "API for zenius simfile site"
authors = ["Raeed Ahmed <code@raeed.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
beautifulsoup4 = "^4.12.3"
lxml = "^5.1.0"
requests = "^2.31.0"
iterfzf = "*"
loguru = "^0.7.2"
questionary = "^2.0.1"

[tool.poetry.group.dev.dependencies]
mypy = "^1.8.0"
ruff = "^0.2.1"
ipykernel = "^6.29.2"
types-requests = "^2.32.0.20240622"
types-beautifulsoup4 = "^4.12.0.20240511"

[tool.poetry.scripts]
zenius = "zenius.vanisher:main"
smonline = "zenius.smonline:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
venvPath = "."
venv = ".venv"
