[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mandelbrot-viewer"
version = "0.1.13"
description = "An arbitrary precision GPU accelerated mandelbrot set viewer buit with kivy and taichi."
readme = "README.md"
authors = [
  { name="BalÃ¡zs Szalai", email="balazs.backup.2@gmail.com" }
]
requires-python = ">=3.9"
dependencies = [
    "cython",
    "taichi-big-float>=0.1.3",
    "kivy",
    "sympy",
    "matplotlib",
    "numpy",
    "opencv-python"
]

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools.package-data]
"mandelbrot_viewer" = ["*.kv"]

[project.scripts]
mandelbrot-viewer-cli = "mandelbrot_viewer.mandelbrot_viewer_main:main"
mandelbrot-remote-server = "mandelbrot_viewer.remote_server:main"

[project.gui-scripts]
mandelbrot-viewer = "mandelbrot_viewer.mandelbrot_viewer_main:main"

[project.urls]
"Homepage" = "https://github.com/balazs-szalai/mandelbrot-set-viewer"
