[project]
name = "hexcore"
version = "1.0.0"
authors = [
  { name="David Latosefki (Indroic)", email="indroic@outlook.com" },
]
description = "Núcleo reutilizable para proyectos Python con arquitectura hexagonal y event handling. Provee abstracciones, utilidades y contratos para DDD, eventos y desacoplamiento de infraestructura."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiosqlite>=0.21.0",
    "alembic>=1.16.5",
    "async-typer>=0.1.10",
    "asyncpg>=0.30.0",
    "beanie>=2.0.0",
    "fastapi>=0.116.1",
    "pika>=1.3.2",
    "pydantic>=2.11.7",
    "redis>=6.4.0",
    "sqlalchemy>=2.0.43",
    "typer>=0.17.3",
]

license = "MIT"
license-files = ["LICEN[CS]E*"]


[project.scripts]
hexcore = "hexcore.__main__:app"

[dependency-groups]
dev = [
    "bumpver>=2025.1131",
    "mypy>=1.17.1",
    "ruff>=0.12.11",
]

[tool.bumpver]
current_version = "1.0.0"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "Nueva Version {old_version} -> {new_version}"
tag_message = "{new_version}"
tag_scope = "default"
pre_commit_hook = ""
post_commit_hook = ""
commit = true
tag = true
push = true

[tool.bumpver.file_patterns]
"pyproject.toml" = [
    '^version = "{version}"',
    '^current_version = "{version}"',
]
"README.md" = [
    "**Versión:** {version}",
]

[tool.setuptools]

[tool.setuptools.packages.find]
where = ["."]
