[project]
name = "neurojack"
version = "0.1.1"
description = ""
authors = [
    {name = "dafaqboomduck"}
]
readme = "README.md"
requires-python = ">=3.10, <3.11"
dependencies = [
    "numpy (==2.0.1)",
    "matplotlib (==3.10.5)",
    "tqdm (==4.67.1)",
    "tensorflow-io-gcs-filesystem (>0.28.0,<0.30.0)",
    "tensorflow (==2.18.0)",
    "matplotlib-inline (>=0.1.7,<0.2.0)",
]

[tool.poetry]
packages = [{include = "neurojack"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
