[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "platega"
version = "0.1.0"
authors = [
  { name="ploki1337", email="ploki1337@gmail.com" },
]
description = "A simple and unofficial SDK for the Platega.io API."
readme = "README.md"
requires-python = ">=3.8"
license = { file = "LICENSE" }
keywords = ["platega", "api", "sdk", "payment"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

dependencies = [
    "requests~=2.32.5",
    "pydantic~=2.11.9"
]

[project.urls]
"Homepage" = "https://github.com/ploki1337/platega"

[tool.setuptools.packages.find]
where = ["."]
include = ["platega*"]