[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
[project]
name = "pycode-info"
description = "A tool to analyze Python code complexity and style."
authors = [
    { name = "Justus", email = "justus.d2025@gmail.com" }
]

readme = "README.md"
requires-python = ">=3.8"
license = { file = "LICENSE" }

dynamic = ["dependencies", "version"]
[tool.setuptools.dynamic]
dependencies = { file = "requirements.txt" }
version = { attr = "pycode_info.__version__"}
[project.urls]
homepage = "https://github.com/justusdecker/pycode-info"

