[project]
name = "json-to-ical"
version = "2025.1.1"
description = "Script to convert json calendar data to ical format"
readme = "README.md"
license = "GPL-2.0-or-later"
license-files = ["LICEN[CS]E*",]
requires-python = ">=3.9"
authors = [
    {name = "Ben Fitzhardinge", email = "ben@benjamin.dog"}
]
maintainers = [
    {name = "Ben Fitzhardinge", email = "ben@benjamin.dog"}
]
classifiers = [
  # How mature is this project? Common values are
  #   3 - Alpha
  #   4 - Beta
  #   5 - Production/Stable
  "Development Status :: 4 - Beta",

  # Indicate who your project is intended for
  "Intended Audience :: Developers",

  # Specify the Python versions you support here.
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
]

dependencies = [
    "ical>=4.5.4"
]

[project.scripts]
json-to-ical = "json_to_ical.main:main"

[project.urls]
Homepage = "https://github.com/bendog/pyconau-ical"
Repository = "https://github.com/bendog/pyconau-ical.git"

[build-system]
requires = ["uv_build>=0.8.11"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "uv-publish>=1.3",
]
