[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "gradus"
version = "1.0.1"
description = "Audio steganography tool using phase coding"
readme = "README.md"
requires-python = ">=3.7"
license = {text = "MIT"}
authors = [
    {name = "kaizoku73", email = "ultimate0134@gmail.com"}
]
maintainers = [
    {name = "kaizoku73", email = "ultimate0134@gmail.com"}
]
keywords = ["steganography", "audio", "phase-coding", "cryptography", "security", "wav", "phase-manipulation"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: End Users/Desktop",
    "Topic :: Security :: Cryptography",
    "Topic :: Multimedia :: Sound/Audio",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy>=2.3.2",
    "pillow>=11.3.0",
    "pycryptodome>=3.23.0"
]

[project.urls]
Homepage = "https://github.com/kaizoku73/Gradus"
Repository = "https://github.com/kaizoku73/Gradus"
"Bug Reports" = "https://github.com/kaizoku73/Gradus/issues"
Documentation = "https://kaizoku.gitbook.io/steganography/histogram-shift-in-image"

[project.scripts]
gradus = "gradus.cli:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["gradus*"]
exclude = ["tests*"]

[tool.setuptools.package-data]
gradus = ["*.py"]