[project]
license = "Unlicense"
name = "mkast"
version = "1.0.0"
description = "AST generator"
readme = "README.md"
requires-python = ">=3.7"
authors = [{ name = "5cover", email = "thediscover22450@gmail.com" }]
classifiers = [
    "Programming Language :: Python :: 3"
]
dependencies = [
    "pydantic>=2",
    "PyYAML>=6",
]

[project.scripts]
mkast = "mkast.__main__:main"

[project.urls]
"Homepage" = "https://github.com/5cover/mkast"
"Source" = "https://github.com/5cover/mkast"
"Bug Reports" = "https://github.com/5cover/mkast/issues"

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "--cov"
testpaths = ["tests"]

[tool.mypy]
mypy_path = "src"
ignore_missing_imports = true

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["mkast*"]
exclude = ["tests*", "test*"]

[tool.setuptools.package-data]
mkast = ["schemas/*.json"]



[tool.isort]
profile = "black"

[tool.ruff.per-file-ignores]
"__init__.py" = ["E402", "F401"]
