
[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "olab_prediction_market_sdk"
version = "0.1.1"
description = "OpinionLabs Prediction Market SDK(beta)"
authors = [
    { name = "nik_opinionlabs", email = "nik@opinionlabs.xyz" }
]
dependencies = [
    "urllib3 >= 2.3.0",
    "six >= 1.17.0",
    "certifi >= 2024.12.14",
    "python-dateutil >= 2.9.0.post0",
    "hexbytes >= 1.2.1",
    "web3 >= 7.6.1",
    "eth_account >= 0.13.0",
    "poly_eip712_structs >= 0.0.1",
    "olab_open_api >= 0.0.13"
]