
[project]
name = "HandsON-BuildHat-API"
version = "1.0.16"
description = "A third-party API for controlling LEGO SPIKE devices"
authors = [
  { name="HaNeul Jung", email="hnjung@handsontech.co.kr" }
]
license = {text = "Proprietary - Personal/Educational Use Only"}
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "pyserial>=3.5"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: Other/Proprietary License",
    "Operating System :: OS Independent",
]