[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "search-cli-pro"
version = "0.1.5"
description = "A simple cross-platform CLI tool to search the web from your terminal"
authors = [
    { name = "Hrishikesh Tiwari", email = "tiwarihrishikesh686@gmail.com" }
]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.7"
keywords = ["cli", "search", "browser", "google", "duckduckgo", "bing"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"
]
dependencies = [
    "requests>=2.31.0",
    "beautifulsoup4>=4.12.0",
    "InquirerPy>=0.3",
    "rich>=13.5.2"
]

[project.scripts]
search = "searchcli.cli:main"
