[tool.poetry]
name = "open-balpy"
version = "0.1.6"
description = "Balancer V2 Python API"
authors = ["Greg <greg@orb.cl>", "8baller <8baller@station.codes>"]
readme = "README.md"
license = "GNU GPL 3"
packages = [
    { include = "balpy", from = "." },
]

[tool.poetry.dependencies]
python = ">=3.9,<4"
Cython=">=0.29.24"
cytoolz=">=0.11.2"
requests=">=2.25.1"
eth-abi=">=2.1.1"
gql=">=2.0.0"
jstyleson=">=0.0.2"
web3=">=6.0.0"
open-multicaller=">=0.2.0"
requests-toolbelt = "^1.0.0"

[tool.poetry.group.dev.dependencies]
pytest="*"
click = "8.0.2"
setuptools = "^68.2.2"
tbump = "^6.11.0"
ruff = "^0.12.9"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
