
[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "HoloSTT"
version = "0.2.4"
description = """
Modern Speech Recognition with both active and ambient listening and keyboard 
input capabilities for modern AI-driven applications."""
authors = [
  {name = "Tristan McBride Sr.", email = "142635792+TristanMcBrideSr@users.noreply.github.com"},
]
maintainers = [
  {name = "Tristan McBride Sr.", email = "142635792+TristanMcBrideSr@users.noreply.github.com"}
]
readme = "README.md"
license = "Apache-2.0"
license-files = ["LICEN[CS]E.*"]
requires-python = ">=3.10"
dependencies = [
    "SpeechRecognition",
    "requests",
    "faster-whisper",
    "torch",
    "pyaudio",
    "numpy",
]
# Optional: Use this if you want to expose keywords for searchability
keywords = [
    "AI", "Agents", "Speech Recognition", "Productivity", "Automation"
]
# Optional: Classifiers for PyPI
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
]

[project.urls]
Homepage = "https://github.com/TristanMcBrideSr"
