[dependency-groups]
dev = [
    "coverage>=7.10.6",
    "pytest>=8.4.2",
    "ruff>=0.12.12",
    "ssort>=0.15.0",
    "toml-sort>=0.24.2",
]

[project]
name = "drug_toxicity"
version = "0.2.0"
authors = [
    { name = "Hester Chapman", email = "hester.chapman@btinternet.com" },
]
description = "Drug metabolism and toxicity prediction."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "molvs>=0.1.1",
    "pubchempy>=1.0.4",
    "rdkit>=2025.3.6",
]
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/HettieC/DrugToxicity"
Issues = "https://github.com/HettieC/DrugToxicity/issues"

[tool.hatchling]
from = "src"
include = ["drug_toxicity"]

[tool.ruff]
indent-width = 4
line-length = 88

[tool.ruff.lint]
select = ["ALL"]
fixable = ["ALL"]
ignore = [
    "ANN401",  # any
    "C901",    # too complex
    "COM812",  # missing trailing comma
    "D105",    # magic methods
    "D203",    # blank line before docstring
    "D213",    # multi-line summary first line
    "D401",    # first line should be in imperative mood
    "E501",    # line-too-long
    "ERA001",  # commented-out code
    "ISC001",  # single line implicit string concat
    "N806",    # non-lowercase variable
    "PGH003",  # specific rule type ignore
    "S110",    # try-except-pass
    "S301",    # pickle usage
    "TD001",   # invalid todo tag
    "TD002",   # missing todo author
    "TD003",   # missing todo link
    "TD004",   # missing todo version
    "TD005",   # missing todo date
    "TRY003",  # raise vanilla args
    "TRY300",  # extra else block
    "PLR0912", # too many branches
    "PLR0911", # too many statements
    "PLR0913", # max num of arguments
    "PLR0915", # too many lines
    "PD010",   # pivot table
    "PT011",   # pytest.raises is too broad
    "RUF022",  # unsorted all
    "TC006",   # cast("type")
]

[tool.ruff.lint.per-file-ignores]
"*.ipynb" = [
    "T201", # print statements
    "D",    # all of documentation
]
"tests/*" = [
    "S101",    # assert
    "D",       # all of documentation
    "PLR2004", # magic comparisons
    "SLF",
    "PD901",   # "df" name
]
"tmp/*" = [
    "I001", # unsorted imports
    "S101", # assert
    "D",    # all of documentation
    "N",    # all of naming
]

[tool.tomlsort]
spaces_before_inline_comment = 2
spaces_indent_inline_array = 2
trailing_comma_inline_array = true

[tool.uv]
package = true

[tool.uv.sources]
drug_toxicity = { workspace = true }
