[tool.poetry]
name = "anomavision"
version = "3.0.10"  # Major version bump for breaking change
description = "Advanced Anomaly Detection Environment - Deep learning library for state-of-the-art anomaly detection algorithms"
authors = ["Deep Knowledge <Deepp.Knowledge@gmail.com>"]
readme = "README.md"

license = "MIT"
keywords = ["anomaly", "vision", "computer-vision", "anomaly-detection","PaDim"]
homepage = "https://github.com/DeepKnowledge1"
repository = "https://github.com/DeepKnowledge1/AnomaVision"
documentation = "https://github.com/DeepKnowledge1/AnomaVision/wiki"


packages = [
    {include = "anomavision"},
    {include = "anodet"},  # Backward compatibility layer
]

[tool.poetry.dependencies]
python = "^3.9"
paho-mqtt = "1.6.1"
matplotlib = "3.8.3"
numpy = "1.26.4"
gitpython = "3.1.42"
albumentations = "1.4.0"
pycocotools = "2.0.7"
ipython = "8.18.1"
openvino-dev = "2023.0"
easydict = "1.13"
pandas = "^2.2.2"
py-cpuinfo = "^9.0.0"
thon = "^2.2"
psutil = "^5.9.8"
onnx = "1.14.1"
onnxruntime-gpu = "1.14.1"

#torch = { version = "1.13.1+cu117", source="torch"}
#torchaudio = { version = "^0.13.1+cu117", source="torch"}
#torchvision = { version = "0.14.1+cu117", source="torch"}
torch = "^1.13.1"
torchaudio = "^0.13.1"
torchvision = "^0.14.1"


opencv-python = [
    { version = "^4.6.0", markers = "sys_platform == 'win32'"},
    { version = "^4.6.0", markers = "sys_platform == 'linux'" }
]
#visionpublisher = {git = "https://ac-it-mvs@dev.azure.com/ac-it-mvs/crd-swec/_git/VisionPublisher", rev = "v0.1.5"}
uvicorn = "^0.34.3"
python-multipart = "^0.0.20"
seaborn = "^0.13.2"
tabulate = "^0.9.0"
tqdm = "^4.67.1"

[tool.poetry.group.dev.dependencies]
pytest = "8.0.2"
black = "24.2.0"
flake8 = "7.0.0"
pre-commit = "3.6.2"
tox = "4.13.0"
ipykernel = "^6.29.5"
twine = "^6.2.0"



[[tool.poetry.source]]
name = "torch"
url = "https://download.pytorch.org/whl/cu117"
priority = "supplemental"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
