[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "keyboardkey"
version = "3.0"
description = "A module providing lists of real keyboard keys."
license = { text = "MIT" }
readme = "README.md"
authors = [{ name = "Aaron Geo Reji" }]
keywords = ["keyboard", "keys", "python", "keyboardkey", "key"]
requires-python = ">=3.7"
