[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "anyads"
version = "1.1.5"
authors = [
    { name="MaoMedia AnyAds"},
]
description = "Official SDK for the AnyAds advertising platform for Telegram bots."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Framework :: AsyncIO",
    "Intended Audience :: Developers",
]

dependencies = [
    "httpx[http2]>=0.25.0",
    "getmac>=0.9.0"
]

[project.urls]
"Homepage" = "https://anyads.online"
"Documentation" = "https://wiki.anyads.online"

[project.optional-dependencies]
aiogram = [
    "aiogram>=3.0.0"
]