[project]
name = "alens-importers"
version = "0.10.0"
description = "Importers for Beancount's beangulp"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beancount>=3.1.0",
    "beangulp>=0.2.0",
    "ibflex",
    "loguru>=0.7.3",
    "requests>=2.32.3",
]

#[project.optional-dependencies]
[dependency-groups]
dev = [
    "pytest>=8.3.5",
]

[project.urls]
repository = "https://github.com/alensiljak/alens-importers"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
# include = ["alens_importers"]
packages = ["src/alens/"]

# Used for a direct reference to beangulp. Remove after beangulp package is published.
[tool.hatch.metadata]
allow-direct-references = true

[tool.ruff]

[tool.uv.sources]
ibflex = { git = "https://github.com/csingley/ibflex" }
