[tool.black]
line-length = 120
target-version = ['py310']
exclude = '''(/(.git|venv|dist)/)'''

[tool.isort]
profile = "black"
line_length = 120

[tool.ruff]
line-length = 120

[tool.poetry]
name = "edos"
version = "1.13.0"
description = "Internal tool for managing docker swarm cluster and DO services"
authors = ["Štěpán Binko <stepanjr@binko.cz>"]

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.1.7"
appdirs = "^1.4.4"
PyYAML = "^6.0"
boto3 = "^1.34.159"
docker = "^7.1.0"
paramiko = "^3.4.1"
diskcache = "^5.6.3"
tabulate = "^0.9.0"
fakturoid = "^1.5.1"
clockify-api-client = "^0.1.0"
python-dateutil = "^2.8.2"
httpx = "^0.27.0"

[tool.poetry.dev-dependencies]
coverage = "^7.0"
pytest = "^7.1.2"
pytest-factoryboy = "^2.3.1"
pre-commit = "^3.0.0"
pytest-cov = "^4.0.0"

[tool.poetry.group.dev.dependencies]
ruff = "^0.4.0"

[build-system]
requires = ["poetry-core>=1.4.0"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.plugins] # Optional super table

[tool.poetry.plugins.console_scripts]
"edos" = "edos.main:main"
"edos-configure" = "edos.config:configure_interactive"
